<?php
define('VERSION',		'2.0');

define('TIME_ZONE',		'Asia/Tokyo');

/* DB related */
define('DB_HOSTNAME',		'localhost');
define('DB_USER',		'root');
define('DB_PASSWORD',		'');
define('DB_NAME',		'judobase');
define('DB_PORT',		3306);

/* e-mail related */
define('MAIL_ENABLE',			1); // 0: disable 1:enable
define('MAIL_FROM',		'test');
define('MAIL_FROMNAME',		'保育園システム運営事務局');
define('MAIL_SMTP_AUTH',		true);
define('MAIL_SMTP_USE_SSL',		false);
define('MAIL_SMTP_SERVER',		'');
define('MAIL_SMTP_USER',		'');
define('MAIL_SMTP_PASSWORD',		'');
define('MAIL_SMTP_PORT',		'25');

/* language */
define('DEFAULT_LANGUAGE',		'ja_jp');
?>
